# : Manager [[[

[mgr]
cwd = { fg = "#c4c19e" }

# Tab
tab_active = { fg = "#9ec3c4", bg = "#8aabac", bold = true }
tab_inactive = { fg = "#9ec3c4", bg = "#262626" }
tab_width = 1

# Find
find_keyword = { fg = "#ac8a8c", bold = true, italic = true, underline = true }
find_position = { fg = "#ac8a8c", bold = true, italic = true }

# Marker
marker_copied = { fg = "#c49ec4", bg = "#c49ec4" }
marker_cut = { fg = "#c49ec4", bg = "#c49ec4" }
marker_marked = { fg = "#ac8a8c", bg = "#ac8a8c" }
marker_selected = { fg = "#c49ec4", bg = "#c49ec4" }

# Count
count_copied = { fg = "#191919", bg = "#c49ec4" }
count_cut = { fg = "#191919", bg = "#c49ec4" }
count_selected = { fg = "#9ec3c4", bg = "#c49ec4" }

# Border
border_symbol = "│"
border_style  = { fg = "#8aabac" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#9ec3c4", fg = "#c6a679" }

[mode]
# Mode
normal_main = { bg = "#8aabac", fg = "#9ec3c4", bold = true }
normal_alt  = { bg = "#262626", fg = "#9ec3c4" }

# Select mode
select_main = { bg = "#9ec3c4", fg = "#9ec3c4", bold = true }
select_alt  = { bg = "#262626", fg = "#9ec3c4" }

# Unset mode
unset_main = { bg = "#c49ec4", fg = "#8f8aac", bold = true }
unset_alt  = { bg = "#262626", fg = "#9ec3c4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#8aabac", bg = "#262626" }
progress_error = { fg = "#ac8a8c", bg = "#262626" }

# Permissions
permissions_t = { fg = "#9ec3c4" }
permissions_w = { fg = "#8f8aac" }
permissions_x = { fg = "#ac8a8c" }
permissions_r = { fg = "#a39ec4" }
permissions_s = { fg = "#9ec3c4" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#8aabac" }
active = { fg = "#c49ec4", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#8aabac" }
value = { fg = "#c4c19e" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#8aabac", bg = "#9ec3c4" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#8aabac" }
title = {}
hovered = { fg = "#c49ec4", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#262626" }
cand = { fg = "#8aabac" }
rest = { fg = "#9ec3c4" }
desc = { fg = "#c4c19e" }
separator = " ▶ "
separator_style = { fg = "#c4c19e" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#c4c19e" }
run = { fg = "#c4c19e" }
footer = { fg = "#9ec3c4", bg = "#9ec3c4" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c49ec4" }
title_warn = { fg = "#8aabac" }
title_error = { fg = "#ac8a8c" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#9ec3c4" },

    # Media
    { mime = "{audio,video}/*", fg = "#aca98a" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ac8aac" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#8aac8b" },

    # Special files
    { name = "*", is = "orphan", bg = "#ac8a8c" },
    { name = "*", is = "exec", fg = "#c49ea0" },

    # Fallback
    { name = "*", fg = "#c4c19e" },
    { name = "*/", fg = "#8aabac" },
]

# : ]]]
